# Generated by Django 6.0.3 on 2026-04-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='决策发生的时间', verbose_name='决策时间')),
                ('trade_date', models.DateField(help_text='对应的交易日期', verbose_name='交易日期')),
                ('decision_type', models.CharField(choices=[('system', '系统决策'), ('manual', '人工干预'), ('override', '系统覆盖人工'), ('deviation', '偏差决策')], help_text='决策的来源类型', max_length=20, verbose_name='决策类型')),
                ('action', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('add', '加仓'), ('reduce', '减仓'), ('hold', '持有'), ('switch', '切换'), ('none', '无操作')], help_text='决策的操作类型', max_length=20, verbose_name='操作')),
                ('quantity', models.IntegerField(blank=True, help_text='建议交易数量', null=True, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='建议成交价格', max_digits=12, null=True, verbose_name='价格')),
                ('decision_rationale', models.TextField(blank=True, help_text='做出此决策的理由', verbose_name='决策依据')),
                ('scores_at_decision', models.JSONField(blank=True, default=dict, help_text='决策时各层得分情况', verbose_name='当时得分')),
                ('execution_status', models.CharField(choices=[('pending', '待执行'), ('executed', '已执行'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', help_text='决策的执行状态', max_length=20, verbose_name='执行状态')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('is_manual_override', models.BooleanField(default=False, help_text='是否有人工干预此决策', verbose_name='是否人工干预')),
                ('override_reason', models.TextField(blank=True, help_text='人工干预的原因', verbose_name='干预原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_decisions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('from_etf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs_from', to='portfolio.etf', verbose_name='卖出品种')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_decisions', to=settings.AUTH_USER_MODEL, verbose_name='干预人')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='monitor.signal', verbose_name='关联信号')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='monitor.monitorstrategy', verbose_name='关联策略')),
                ('to_etf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs_to', to='portfolio.etf', verbose_name='买入品种')),
            ],
            options={
                'verbose_name': '决策日志',
                'verbose_name_plural': '决策日志',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='偏差时间')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('deviation_type', models.CharField(choices=[('override', '人工覆盖'), ('delayed', '延迟执行'), ('skipped', '跳过交易'), ('modified', '修改参数'), ('additional', '额外交易'), ('no_deviation', '无偏差')], help_text='偏差的类型', max_length=20, verbose_name='偏差类型')),
                ('description', models.TextField(help_text='偏差的详细描述', verbose_name='偏差描述')),
                ('reason', models.TextField(help_text='产生偏差的主观/客观原因', verbose_name='偏差原因')),
                ('system_action', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('add', '加仓'), ('reduce', '减仓'), ('hold', '持有'), ('switch', '切换'), ('none', '无操作')], help_text='系统建议的操作', max_length=20, verbose_name='系统操作')),
                ('actual_action', models.CharField(blank=True, choices=[('buy', '买入'), ('sell', '卖出'), ('add', '加仓'), ('reduce', '减仓'), ('hold', '持有'), ('switch', '切换'), ('none', '无操作')], help_text='实际执行的操作', max_length=20, null=True, verbose_name='实际操作')),
                ('verification_deadline', models.DateField(blank=True, help_text='需要完成验证的日期', null=True, verbose_name='验证截止日期')),
                ('verification_result', models.CharField(choices=[('pending', '待验证'), ('correct', '判断正确'), ('wrong', '判断错误'), ('uncertain', '无法确定')], default='pending', help_text='逆向验证的结果', max_length=20, verbose_name='验证结果')),
                ('verification_notes', models.TextField(blank=True, help_text='验证过程的详细记录', verbose_name='验证备注')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('system_pnl', models.DecimalField(blank=True, decimal_places=4, help_text='如果按系统决策执行的实际盈亏', max_digits=20, null=True, verbose_name='系统决策盈亏')),
                ('actual_pnl', models.DecimalField(blank=True, decimal_places=4, help_text='实际执行的盈亏', max_digits=20, null=True, verbose_name='实际决策盈亏')),
                ('pnl_difference', models.DecimalField(blank=True, decimal_places=4, help_text='实际盈亏 - 系统盈亏（负值表示偏离导致亏损）', max_digits=20, null=True, verbose_name='盈亏差异')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actual_decision', models.ForeignKey(blank=True, help_text='实际执行的决策', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviation_as_actual', to='journal.decisionlog', verbose_name='实际决策')),
                ('actual_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviation_actual_targets', to='portfolio.etf', verbose_name='实际目标品种')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deviations', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('system_decision', models.ForeignKey(help_text='系统建议的决策', on_delete=django.db.models.deletion.CASCADE, related_name='deviation_as_system', to='journal.decisionlog', verbose_name='系统决策')),
                ('system_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviation_system_targets', to='portfolio.etf', verbose_name='系统目标品种')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deviations', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
            ],
            options={
                'verbose_name': '偏差日志',
                'verbose_name_plural': '偏差日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
