# Generated by Django 6.0.3 on 2026-04-05 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('monitor', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='正数为多头，负数为空头', verbose_name='持仓数量')),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, help_text='持仓平均成本', max_digits=10, verbose_name='平均成本')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='持仓总成本', max_digits=15, verbose_name='总成本')),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='当前市值', max_digits=15, null=True, verbose_name='市值')),
                ('unrealized_pnl', models.DecimalField(blank=True, decimal_places=2, help_text='未实现盈亏', max_digits=15, null=True, verbose_name='未实现盈亏')),
                ('unrealized_pnl_pct', models.DecimalField(blank=True, decimal_places=4, help_text='未实现收益率百分比', max_digits=10, null=True, verbose_name='未实现收益率(%)')),
                ('first_trade_time', models.DateTimeField(blank=True, null=True, verbose_name='首次建仓时间')),
                ('last_trade_time', models.DateTimeField(blank=True, null=True, verbose_name='最后交易时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否还有持仓', verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.etf', verbose_name='品种')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='journal_pos_user_id_e8e927_idx'), models.Index(fields=['etf', '-updated_at'], name='journal_pos_etf_id_1d943f_idx'), models.Index(fields=['is_active', '-updated_at'], name='journal_pos_is_acti_f00399_idx')],
                'unique_together': {('user', 'etf')},
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, help_text='实际交易发生的时间', verbose_name='交易时间')),
                ('trade_date', models.DateField(help_text='对应的交易日期', verbose_name='交易日期')),
                ('action', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('add', '加仓'), ('reduce', '减仓')], help_text='交易操作类型', max_length=20, verbose_name='操作类型')),
                ('quantity', models.PositiveIntegerField(help_text='交易数量', verbose_name='数量（股）')),
                ('price', models.DecimalField(decimal_places=4, help_text='实际成交价格', max_digits=10, verbose_name='成交价（元）')),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='交易手续费', max_digits=10, verbose_name='手续费（元）')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='总成交金额（含手续费）', max_digits=15, verbose_name='总金额（元）')),
                ('match_signal', models.BooleanField(default=True, help_text='是否与系统信号一致', verbose_name='与信号一致')),
                ('deviation_note', models.TextField(blank=True, help_text='如果与信号不一致，说明原因', verbose_name='偏差说明')),
                ('note', models.TextField(blank=True, help_text='其他备注信息', verbose_name='交易备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trade_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_records', to='portfolio.etf', verbose_name='品种')),
                ('related_deviation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_records', to='journal.deviationlog', verbose_name='关联偏差记录')),
                ('related_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_records', to='monitor.signal', verbose_name='关联信号')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_trade_records', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-trade_time'],
                'indexes': [models.Index(fields=['-trade_time'], name='journal_tra_trade_t_047968_idx'), models.Index(fields=['etf', '-trade_time'], name='journal_tra_etf_id_f4adad_idx'), models.Index(fields=['action', '-trade_time'], name='journal_tra_action_103e4e_idx'), models.Index(fields=['match_signal', '-trade_time'], name='journal_tra_match_s_14aa5e_idx')],
            },
        ),
    ]
