# Generated by Django 6.0.3 on 2026-04-01 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('code', models.CharField(help_text='ETF代码，如510300', max_length=10, primary_key=True, serialize=False, verbose_name='ETF代码')),
                ('name', models.CharField(help_text='ETF名称，如沪深300ETF', max_length=100, verbose_name='ETF名称')),
                ('market', models.CharField(choices=[('SH', '上海证券交易所'), ('SZ', '深圳证券交易所')], help_text='ETF上市市场', max_length=2, verbose_name='所属市场')),
                ('category', models.CharField(choices=[('equity', '权益型'), ('bond', '债券型'), ('commodity', '商品型'), ('money_market', '货币市场型'), ('cross_border', '跨境型'), ('sector', '行业主题型')], help_text='ETF基金类别', max_length=20, verbose_name='ETF类别')),
                ('tracking_index', models.CharField(blank=True, help_text='ETF跟踪的指数名称', max_length=100, verbose_name='跟踪指数')),
                ('tracking_index_code', models.CharField(blank=True, help_text='跟踪指数代码', max_length=20, verbose_name='跟踪指数代码')),
                ('fund_manager', models.CharField(blank=True, help_text='ETF管理人', max_length=100, verbose_name='基金管理人')),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='年化管理费率', max_digits=5, null=True, verbose_name='管理费率')),
                ('is_active', models.BooleanField(default=True, help_text='ETF是否在交易', verbose_name='是否活跃')),
                ('list_date', models.DateField(blank=True, help_text='ETF上市日期', null=True, verbose_name='上市日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ETF品种',
                'verbose_name_plural': 'ETF品种',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('code', models.CharField(help_text='品种池唯一标识', max_length=20, primary_key=True, serialize=False, verbose_name='池代码')),
                ('name', models.CharField(help_text='品种池显示名称', max_length=100, verbose_name='池名称')),
                ('description', models.TextField(blank=True, help_text='品种池的详细描述', verbose_name='池描述')),
                ('purpose', models.CharField(choices=[('rotation', 'ETF轮动'), ('permanent', '永久组合'), ('thematic', '主题仓位'), ('custom', '自定义')], help_text='品种池的使用目的', max_length=20, verbose_name='池用途')),
                ('asset_classes', models.JSONField(blank=True, default=dict, help_text='各资产类别的目标配置比例，如{"equity": 0.4, "bond": 0.3}', verbose_name='资产类别配置')),
                ('is_active', models.BooleanField(default=True, help_text='品种池是否可用', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品种池',
                'verbose_name_plural': '品种池',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ETFPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(default=0, verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='成交额')),
                ('adj_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='复权因子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.etf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': 'ETF价格数据',
                'verbose_name_plural': 'ETF价格数据',
                'ordering': ['etf', '-date'],
                'indexes': [models.Index(fields=['etf', 'date'], name='portfolio_e_etf_id_8dbed2_idx'), models.Index(fields=['date'], name='portfolio_e_date_32757e_idx')],
                'unique_together': {('etf', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=4, default=0.0, help_text='该ETF在池中的目标配置比例（0-1）', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='目标权重')),
                ('thresholds', models.JSONField(blank=True, default=dict, help_text='该ETF的自定义阈值配置，如{"L1-02": {"ema_period": 60}}', verbose_name='阈值配置')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='该ETF的筛选条件，如{"min_volume": 1000000, "min_price": 1.0}', verbose_name='筛选条件')),
                ('order', models.PositiveIntegerField(default=0, help_text='池中显示顺序', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='该成员是否参与计算', verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, help_text='该成员的备注说明', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to='portfolio.etf', verbose_name='ETF品种')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portfolio.pool', verbose_name='所属池')),
            ],
            options={
                'verbose_name': '池成员',
                'verbose_name_plural': '池成员',
                'ordering': ['pool', 'order', 'etf'],
                'unique_together': {('pool', 'etf')},
            },
        ),
    ]
