# Generated by Django 6.0.3 on 2026-04-01 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='回测任务的名称', max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, help_text='回测任务的详细描述', verbose_name='任务描述')),
                ('task_code', models.SlugField(help_text='任务的唯一标识代码', unique=True, verbose_name='任务代码')),
                ('strategy_type', models.CharField(choices=[('rotation', 'ETF轮动'), ('permanent', '永久组合'), ('thematic', '主题仓位'), ('custom', '自定义策略')], help_text='回测使用的策略类型', max_length=20, verbose_name='策略类型')),
                ('start_date', models.DateField(help_text='回测开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='回测结束日期', verbose_name='结束日期')),
                ('in_sample_ratio', models.DecimalField(decimal_places=2, default=0.7, help_text='样本内数据占比（默认70%）', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.9)], verbose_name='样本内比例')),
                ('initial_capital', models.DecimalField(decimal_places=4, default=1000000, help_text='回测初始资金', max_digits=20, verbose_name='初始资金')),
                ('commission_rate', models.DecimalField(decimal_places=5, default=0.001, help_text='交易佣金率（默认0.1%）', max_digits=6, verbose_name='佣金率')),
                ('slippage', models.DecimalField(decimal_places=5, default=0.001, help_text='滑点（默认0.1%）', max_digits=6, verbose_name='滑点')),
                ('weight_override', models.JSONField(blank=True, default=dict, help_text='覆盖默认权重配置，如{"L1": 0.35, "L2": 0.25}', verbose_name='权重覆盖')),
                ('threshold_override', models.JSONField(blank=True, default=dict, help_text='覆盖默认阈值配置', verbose_name='阈值覆盖')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', help_text='回测任务当前状态', max_length=20, verbose_name='任务状态')),
                ('is_active', models.BooleanField(default=True, help_text='任务是否处于启用状态', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('pool', models.ForeignKey(help_text='回测使用的品种池', on_delete=django.db.models.deletion.CASCADE, related_name='backtest_tasks', to='portfolio.pool', verbose_name='品种池')),
            ],
            options={
                'verbose_name': '回测任务',
                'verbose_name_plural': '回测任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('in_sample', '样本内'), ('out_of_sample', '样本外'), ('full', '全量')], help_text='结果对应的样本类型', max_length=20, verbose_name='样本类型')),
                ('is_valid', models.BooleanField(default=True, help_text='此结果是否有效（未被覆盖）', verbose_name='是否有效')),
                ('total_return', models.DecimalField(blank=True, decimal_places=8, help_text='回测期间总收益率', max_digits=15, null=True, verbose_name='总收益率')),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=8, help_text='年化收益率', max_digits=15, null=True, verbose_name='年化收益率')),
                ('benchmark_return', models.DecimalField(blank=True, decimal_places=8, help_text='基准指数收益率', max_digits=15, null=True, verbose_name='基准收益率')),
                ('excess_return', models.DecimalField(blank=True, decimal_places=8, help_text='超越基准的收益', max_digits=15, null=True, verbose_name='超额收益')),
                ('volatility', models.DecimalField(blank=True, decimal_places=8, help_text='年化波动率', max_digits=15, null=True, verbose_name='波动率')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=8, help_text='最大回撤幅度', max_digits=15, null=True, verbose_name='最大回撤')),
                ('max_drawdown_period', models.IntegerField(blank=True, help_text='最大回撤持续的天数', null=True, verbose_name='最大回撤持续期')),
                ('var_95', models.DecimalField(blank=True, decimal_places=8, help_text='95%置信区间的VaR', max_digits=15, null=True, verbose_name='VaR(95%)')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=8, help_text='年化夏普比率', max_digits=15, null=True, verbose_name='夏普比率')),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=8, help_text='索提诺比率', max_digits=15, null=True, verbose_name='索提诺比率')),
                ('calmar_ratio', models.DecimalField(blank=True, decimal_places=8, help_text='卡玛比率', max_digits=15, null=True, verbose_name='卡玛比率')),
                ('treynor_ratio', models.DecimalField(blank=True, decimal_places=8, help_text='特雷诺比率', max_digits=15, null=True, verbose_name='特雷诺比率')),
                ('total_trades', models.IntegerField(blank=True, help_text='回测期间总交易次数', null=True, verbose_name='总交易次数')),
                ('winning_trades', models.IntegerField(blank=True, help_text='盈利的交易次数', null=True, verbose_name='盈利交易次数')),
                ('losing_trades', models.IntegerField(blank=True, help_text='亏损的交易次数', null=True, verbose_name='亏损交易次数')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=4, help_text='盈利交易占比', max_digits=7, null=True, verbose_name='胜率')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=8, help_text='总盈利/总亏损', max_digits=15, null=True, verbose_name='盈亏比')),
                ('avg_trade_return', models.DecimalField(blank=True, decimal_places=8, help_text='每次交易的平均收益', max_digits=15, null=True, verbose_name='平均交易收益')),
                ('avg_winning_trade', models.DecimalField(blank=True, decimal_places=8, help_text='盈利交易的平均收益', max_digits=15, null=True, verbose_name='平均盈利')),
                ('avg_losing_trade', models.DecimalField(blank=True, decimal_places=8, help_text='亏损交易的平均亏损', max_digits=15, null=True, verbose_name='平均亏损')),
                ('is_overfitted', models.BooleanField(default=False, help_text='是否检测到过拟合', verbose_name='是否过拟合')),
                ('in_out_sharpe_ratio', models.DecimalField(blank=True, decimal_places=8, help_text='样本内夏普/样本外夏普', max_digits=15, null=True, verbose_name='样本内外夏普比')),
                ('parameter_count', models.IntegerField(blank=True, help_text='策略参数组合数', null=True, verbose_name='参数数量')),
                ('out_of_sample_trades', models.IntegerField(blank=True, help_text='样本外期间的实际交易次数', null=True, verbose_name='样本外交易次数')),
                ('equity_curve', models.JSONField(blank=True, default=list, help_text='每日权益值序列', verbose_name='权益曲线')),
                ('drawdown_series', models.JSONField(blank=True, default=list, help_text='每日回撤值序列', verbose_name='回撤序列')),
                ('trade_list', models.JSONField(blank=True, default=list, help_text='详细交易记录列表', verbose_name='交易记录')),
                ('monthly_returns', models.JSONField(blank=True, default=dict, help_text='月度收益率统计', verbose_name='月度收益')),
                ('rolling_metrics', models.JSONField(blank=True, default=dict, help_text='滚动窗口计算的各项指标', verbose_name='滚动指标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='backtest.backtesttask', verbose_name='回测任务')),
            ],
            options={
                'verbose_name': '回测结果',
                'verbose_name_plural': '回测结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
