# Generated by Django 6.0.3 on 2026-04-01 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('data_source', '数据源检查'), ('calculation', '指标计算检查'), ('signal', '信号生成检查'), ('database', '数据库检查'), ('notification', '通知服务检查')], help_text='健康检查的类型', max_length=20, verbose_name='检查类型')),
                ('status', models.CharField(choices=[('healthy', '健康'), ('warning', '警告'), ('critical', '严重'), ('unknown', '未知')], help_text='检查结果状态', max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, help_text='检查结果的详细消息', verbose_name='检查消息')),
                ('details', models.JSONField(blank=True, default=dict, help_text='检查的详细数据', verbose_name='详细信息')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='检查的响应时间（毫秒）', null=True, verbose_name='响应时间(ms)')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
            ],
            options={
                'verbose_name': '健康检查日志',
                'verbose_name_plural': '健康检查日志',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='预警规则的名称', max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, help_text='规则的详细描述', verbose_name='规则描述')),
                ('rule_code', models.SlugField(help_text='规则的唯一标识代码', unique=True, verbose_name='规则代码')),
                ('condition_type', models.CharField(help_text='触发条件的类型（如score_drop、drawdown_spike等）', max_length=50, verbose_name='条件类型')),
                ('condition_params', models.JSONField(default=dict, help_text='触发条件的参数', verbose_name='条件参数')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], default='warning', help_text='预警的严重程度', max_length=20, verbose_name='严重级别')),
                ('notification_channels', models.JSONField(default=list, help_text='通知渠道列表（如feishu、email、sms）', verbose_name='通知渠道')),
                ('notification_template', models.TextField(blank=True, help_text='通知消息的模板', verbose_name='通知模板')),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='同一规则的重复触发间隔', verbose_name='冷却时间（分钟）')),
                ('is_active', models.BooleanField(default=True, help_text='规则是否生效', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='监控策略的名称', max_length=200, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, help_text='策略的详细描述', verbose_name='策略描述')),
                ('strategy_code', models.SlugField(help_text='策略的唯一标识代码', unique=True, verbose_name='策略代码')),
                ('strategy_type', models.CharField(choices=[('rotation', 'ETF轮动'), ('permanent', '永久组合'), ('thematic', '主题仓位')], help_text='监控策略的类型', max_length=20, verbose_name='策略类型')),
                ('frequency', models.CharField(choices=[('intraday_10min', '盘中10分钟'), ('daily_1445', '每日14:45'), ('weekly', '每周'), ('monthly', '每月')], help_text='策略信号计算频率', max_length=20, verbose_name='执行频率')),
                ('weight_config', models.JSONField(blank=True, default=dict, help_text='L1-L4权重配置，如{"L1": 0.35, "L2": 0.25}', verbose_name='权重配置')),
                ('threshold_config', models.JSONField(blank=True, default=dict, help_text='各指标的阈值配置', verbose_name='阈值配置')),
                ('entry_rules', models.JSONField(blank=True, default=dict, help_text='入场条件规则', verbose_name='入场规则')),
                ('exit_rules', models.JSONField(blank=True, default=dict, help_text='出场条件规则', verbose_name='出场规则')),
                ('risk_limits', models.JSONField(blank=True, default=dict, help_text='风险控制参数，如{"max_position": 1, "stop_loss": 0.05}', verbose_name='风险限制')),
                ('notification_config', models.JSONField(blank=True, default=dict, help_text='信号通知配置', verbose_name='通知配置')),
                ('is_active', models.BooleanField(default=True, help_text='策略是否处于监控状态', verbose_name='是否启用')),
                ('is_running', models.BooleanField(default=False, help_text='策略是否正在执行', verbose_name='是否运行中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('pool', models.ForeignKey(help_text='监控使用的品种池', on_delete=django.db.models.deletion.CASCADE, related_name='monitor_strategies', to='portfolio.pool', verbose_name='品种池')),
            ],
            options={
                'verbose_name': '监控策略',
                'verbose_name_plural': '监控策略',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='信号生成的时间', verbose_name='信号时间')),
                ('trade_date', models.DateField(help_text='信号对应的交易日期', verbose_name='交易日期')),
                ('signal_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('add', '加仓'), ('reduce', '减仓'), ('hold', '持有'), ('switch', '切换')], help_text='信号的操作类型', max_length=20, verbose_name='信号类型')),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='建议成交价格', max_digits=12, null=True, verbose_name='价格')),
                ('quantity', models.IntegerField(blank=True, help_text='建议成交数量', null=True, verbose_name='数量')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, help_text='建议成交金额', max_digits=20, null=True, verbose_name='金额')),
                ('l1_score', models.DecimalField(blank=True, decimal_places=2, help_text='趋势层得分（0-100）', max_digits=6, null=True, verbose_name='L1得分')),
                ('l2_score', models.DecimalField(blank=True, decimal_places=2, help_text='结构层得分（0-100）', max_digits=6, null=True, verbose_name='L2得分')),
                ('l3_score', models.DecimalField(blank=True, decimal_places=2, help_text='共振层得分（0-100）', max_digits=6, null=True, verbose_name='L3得分')),
                ('l4_score', models.DecimalField(blank=True, decimal_places=2, help_text='缺口层得分（0-100，反向计分）', max_digits=6, null=True, verbose_name='L4得分')),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, help_text='加权综合得分（0-100）', max_digits=6, null=True, verbose_name='综合得分')),
                ('score_details', models.JSONField(blank=True, default=dict, help_text='各层指标的详细计算结果', verbose_name='得分详情')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('executed', '已执行'), ('expired', '已过期'), ('cancelled', '已取消')], default='pending', help_text='信号的当前状态', max_length=20, verbose_name='信号状态')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('executed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='执行价格')),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, help_text='该信号的盈亏金额', max_digits=20, null=True, verbose_name='盈亏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('from_etf', models.ForeignKey(blank=True, help_text='卖出的ETF品种', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals_from', to='portfolio.etf', verbose_name='卖出品种')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='monitor.monitorstrategy', verbose_name='所属策略')),
                ('to_etf', models.ForeignKey(blank=True, help_text='买入的ETF品种', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals_to', to='portfolio.etf', verbose_name='买入品种')),
            ],
            options={
                'verbose_name': '交易信号',
                'verbose_name_plural': '交易信号',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='预警的标题', max_length=200, verbose_name='预警标题')),
                ('message', models.TextField(help_text='预警的详细内容', verbose_name='预警消息')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('critical', '严重')], help_text='预警的严重程度', max_length=20, verbose_name='严重级别')),
                ('trigger_data', models.JSONField(default=dict, help_text='触发预警时的相关数据', verbose_name='触发数据')),
                ('notification_status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('skipped', '已跳过')], default='pending', help_text='通知发送状态', max_length=20, verbose_name='通知状态')),
                ('notification_channels', models.JSONField(default=list, help_text='实际使用的通知渠道', verbose_name='通知渠道')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='通知发送时间')),
                ('notification_error', models.TextField(blank=True, help_text='通知发送失败的错误信息', verbose_name='通知错误')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='是否已被人工确认', verbose_name='是否确认')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='monitor.alertrule', verbose_name='触发规则')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='monitor.monitorstrategy', verbose_name='关联策略')),
            ],
            options={
                'verbose_name': '预警日志',
                'verbose_name_plural': '预警日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'created_at'], name='monitor_ale_severit_748db1_idx'), models.Index(fields=['notification_status', 'created_at'], name='monitor_ale_notific_fb1d9b_idx'), models.Index(fields=['is_acknowledged', 'created_at'], name='monitor_ale_is_ackn_7718bd_idx')],
            },
        ),
    ]
